### ISSUE TITLE
Name as fingerprint only

### ISSUE THREAD

**Issue by Adryd** [tkareine/jekyll-minibundle#13]
A suggestion I have is an option to remove the name and only have the fingerprint; eg.

`{% ministamp { source_path: _assets/site.css, destination_path: assets/xxx.css, fingerprint_only: true} %}` would name the file as only the fingerprint `8e764372a0dbd296033cb2a416f064b5.css` instead of `site-8e764372a0dbd296033cb2a416f064b5.css`

It would help a lot with name conflicts

**Comment by tkareine** [comment]
Could you describe an example scenario where this would be useful?

**Comment by tkareine** [comment]
I'm closing this issue since no further discussion emerged.
