### ISSUE TITLE
Option for multiple paths for source_dir

### ISSUE THREAD

**Issue by pvillanueva01** [tkareine/jekyll-minibundle#14]
First of all, great plugin. I was wondering if there is a way to include multiple paths for source_dir.

**Comment by tkareine** [comment]
Would the following work?

``` liquid
{% minibundle js %}
source_dir: _assets
destination_path: assets/site
assets:
- dir1/dependency
- dir2/app
{% endminibundle %}
```

That is, you would store asset sources in the following paths: `_assets/dir1/dependency.js` and `_assets/dir2/app.js`.

You can also refer to Jekyll site dir itself as the asset source dir (`source_dir: .`) and refer to asset sources relatively from there.

**Comment by tkareine** [comment]
I'm closing this issue since no further discussion emerged. Feel free to ask or comment even after closing the issue.
